name: Assign Code Owner Reviewers

on:
  pull_request:
    branches: [ "master" ]
    types:
      - opened
      - edited

jobs:
  assign-reviewers:
    runs-on: ubuntu-latest
    steps:
    
      # Get PR details and determine code owners
      - name: Get Code Owners
        id: get_code_owners
        uses: peter-evans/repository-dispatch@v2
        with:
          event-type: code-owners

      - name: Assign Code Owner as Reviewer
        if: ${{ steps.get_code_owners.outputs.assignee != '' }}
        uses: peter-evans/assign-reviewer@v2
        with:
          reviewers: ${{ steps.get_code_owners.outputs.assignee }}
